<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="DownloadTextFile.Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
     <div style="width:90%; margin:0 auto;padding-top:25px">
         <pre>clicking the button will bring up a dialog to save the file.  The text file is generated by this c#.net application.</pre>
    <asp:Button ID="Button1" Text="Export" OnClick="ProcessDownload" runat="server" />
    </div>
    </div>
    </form>
</body>
</html>
